/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BetaRecruitmentCriterionOptionsResponse,
  ErrorResponse,
} from '../models';
import {
    BetaRecruitmentCriterionOptionsResponseFromJSON,
    BetaRecruitmentCriterionOptionsResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models';

export interface BetaRecruitmentCriterionOptionsGetCollectionRequest {
    fieldsBetaRecruitmentCriterionOptions?: Array<BetaRecruitmentCriterionOptionsGetCollectionFieldsBetaRecruitmentCriterionOptionsEnum>;
    limit?: number;
}

/**
 * 
 */
export class BetaRecruitmentCriterionOptionsApi extends runtime.BaseAPI {

    /**
     */
    async betaRecruitmentCriterionOptionsGetCollectionRaw(requestParameters: BetaRecruitmentCriterionOptionsGetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BetaRecruitmentCriterionOptionsResponse>> {
        const queryParameters: any = {};

        if (requestParameters.fieldsBetaRecruitmentCriterionOptions) {
            queryParameters['fields[betaRecruitmentCriterionOptions]'] = requestParameters.fieldsBetaRecruitmentCriterionOptions.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("itc-bearer-token", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/betaRecruitmentCriterionOptions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BetaRecruitmentCriterionOptionsResponseFromJSON(jsonValue));
    }

    /**
     */
    async betaRecruitmentCriterionOptionsGetCollection(requestParameters: BetaRecruitmentCriterionOptionsGetCollectionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BetaRecruitmentCriterionOptionsResponse> {
        const response = await this.betaRecruitmentCriterionOptionsGetCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const BetaRecruitmentCriterionOptionsGetCollectionFieldsBetaRecruitmentCriterionOptionsEnum = {
    DeviceFamilyOsVersions: 'deviceFamilyOsVersions'
} as const;
export type BetaRecruitmentCriterionOptionsGetCollectionFieldsBetaRecruitmentCriterionOptionsEnum = typeof BetaRecruitmentCriterionOptionsGetCollectionFieldsBetaRecruitmentCriterionOptionsEnum[keyof typeof BetaRecruitmentCriterionOptionsGetCollectionFieldsBetaRecruitmentCriterionOptionsEnum];
