/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AlternativeDistributionPackageVersionRelationshipsDeltasDataInner } from './AlternativeDistributionPackageVersionRelationshipsDeltasDataInner';
import {
    AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerFromJSON,
    AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerFromJSONTyped,
    AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerToJSON,
} from './AlternativeDistributionPackageVersionRelationshipsDeltasDataInner';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
} from './RelationshipLinks';

/**
 * 
 * @export
 * @interface AlternativeDistributionPackageVersionRelationshipsDeltas
 */
export interface AlternativeDistributionPackageVersionRelationshipsDeltas {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof AlternativeDistributionPackageVersionRelationshipsDeltas
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof AlternativeDistributionPackageVersionRelationshipsDeltas
     */
    meta?: PagingInformation;
    /**
     * 
     * @type {Array<AlternativeDistributionPackageVersionRelationshipsDeltasDataInner>}
     * @memberof AlternativeDistributionPackageVersionRelationshipsDeltas
     */
    data?: Array<AlternativeDistributionPackageVersionRelationshipsDeltasDataInner>;
}

/**
 * Check if a given object implements the AlternativeDistributionPackageVersionRelationshipsDeltas interface.
 */
export function instanceOfAlternativeDistributionPackageVersionRelationshipsDeltas(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AlternativeDistributionPackageVersionRelationshipsDeltasFromJSON(json: any): AlternativeDistributionPackageVersionRelationshipsDeltas {
    return AlternativeDistributionPackageVersionRelationshipsDeltasFromJSONTyped(json, false);
}

export function AlternativeDistributionPackageVersionRelationshipsDeltasFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlternativeDistributionPackageVersionRelationshipsDeltas {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : RelationshipLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerFromJSON)),
    };
}

export function AlternativeDistributionPackageVersionRelationshipsDeltasToJSON(value?: AlternativeDistributionPackageVersionRelationshipsDeltas | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': RelationshipLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(AlternativeDistributionPackageVersionRelationshipsDeltasDataInnerToJSON)),
    };
}

