/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppCustomProductPageVersionInlineCreateRelationshipsAppCustomProductPageLocalizations } from './AppCustomProductPageVersionInlineCreateRelationshipsAppCustomProductPageLocalizations';
import {
    AppCustomProductPageVersionInlineCreateRelationshipsAppCustomProductPageLocalizationsFromJSON,
    AppCustomProductPageVersionInlineCreateRelationshipsAppCustomProductPageLocalizationsFromJSONTyped,
    AppCustomProductPageVersionInlineCreateRelationshipsAppCustomProductPageLocalizationsToJSON,
} from './AppCustomProductPageVersionInlineCreateRelationshipsAppCustomProductPageLocalizations';
import type { AppCustomProductPageVersionRelationshipsAppCustomProductPage } from './AppCustomProductPageVersionRelationshipsAppCustomProductPage';
import {
    AppCustomProductPageVersionRelationshipsAppCustomProductPageFromJSON,
    AppCustomProductPageVersionRelationshipsAppCustomProductPageFromJSONTyped,
    AppCustomProductPageVersionRelationshipsAppCustomProductPageToJSON,
} from './AppCustomProductPageVersionRelationshipsAppCustomProductPage';

/**
 * 
 * @export
 * @interface AppCustomProductPageVersionInlineCreateRelationships
 */
export interface AppCustomProductPageVersionInlineCreateRelationships {
    /**
     * 
     * @type {AppCustomProductPageVersionRelationshipsAppCustomProductPage}
     * @memberof AppCustomProductPageVersionInlineCreateRelationships
     */
    appCustomProductPage?: AppCustomProductPageVersionRelationshipsAppCustomProductPage;
    /**
     * 
     * @type {AppCustomProductPageVersionInlineCreateRelationshipsAppCustomProductPageLocalizations}
     * @memberof AppCustomProductPageVersionInlineCreateRelationships
     */
    appCustomProductPageLocalizations?: AppCustomProductPageVersionInlineCreateRelationshipsAppCustomProductPageLocalizations;
}

/**
 * Check if a given object implements the AppCustomProductPageVersionInlineCreateRelationships interface.
 */
export function instanceOfAppCustomProductPageVersionInlineCreateRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppCustomProductPageVersionInlineCreateRelationshipsFromJSON(json: any): AppCustomProductPageVersionInlineCreateRelationships {
    return AppCustomProductPageVersionInlineCreateRelationshipsFromJSONTyped(json, false);
}

export function AppCustomProductPageVersionInlineCreateRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppCustomProductPageVersionInlineCreateRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appCustomProductPage': !exists(json, 'appCustomProductPage') ? undefined : AppCustomProductPageVersionRelationshipsAppCustomProductPageFromJSON(json['appCustomProductPage']),
        'appCustomProductPageLocalizations': !exists(json, 'appCustomProductPageLocalizations') ? undefined : AppCustomProductPageVersionInlineCreateRelationshipsAppCustomProductPageLocalizationsFromJSON(json['appCustomProductPageLocalizations']),
    };
}

export function AppCustomProductPageVersionInlineCreateRelationshipsToJSON(value?: AppCustomProductPageVersionInlineCreateRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'appCustomProductPage': AppCustomProductPageVersionRelationshipsAppCustomProductPageToJSON(value.appCustomProductPage),
        'appCustomProductPageLocalizations': AppCustomProductPageVersionInlineCreateRelationshipsAppCustomProductPageLocalizationsToJSON(value.appCustomProductPageLocalizations),
    };
}

