/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AlternativeDistributionKeyCreateRequestDataRelationshipsAppData } from './AlternativeDistributionKeyCreateRequestDataRelationshipsAppData';
import {
    AlternativeDistributionKeyCreateRequestDataRelationshipsAppDataFromJSON,
    AlternativeDistributionKeyCreateRequestDataRelationshipsAppDataFromJSONTyped,
    AlternativeDistributionKeyCreateRequestDataRelationshipsAppDataToJSON,
} from './AlternativeDistributionKeyCreateRequestDataRelationshipsAppData';

/**
 * 
 * @export
 * @interface AppEncryptionDeclarationCreateRequestDataRelationshipsApp
 */
export interface AppEncryptionDeclarationCreateRequestDataRelationshipsApp {
    /**
     * 
     * @type {AlternativeDistributionKeyCreateRequestDataRelationshipsAppData}
     * @memberof AppEncryptionDeclarationCreateRequestDataRelationshipsApp
     */
    data: AlternativeDistributionKeyCreateRequestDataRelationshipsAppData;
}

/**
 * Check if a given object implements the AppEncryptionDeclarationCreateRequestDataRelationshipsApp interface.
 */
export function instanceOfAppEncryptionDeclarationCreateRequestDataRelationshipsApp(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function AppEncryptionDeclarationCreateRequestDataRelationshipsAppFromJSON(json: any): AppEncryptionDeclarationCreateRequestDataRelationshipsApp {
    return AppEncryptionDeclarationCreateRequestDataRelationshipsAppFromJSONTyped(json, false);
}

export function AppEncryptionDeclarationCreateRequestDataRelationshipsAppFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppEncryptionDeclarationCreateRequestDataRelationshipsApp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': AlternativeDistributionKeyCreateRequestDataRelationshipsAppDataFromJSON(json['data']),
    };
}

export function AppEncryptionDeclarationCreateRequestDataRelationshipsAppToJSON(value?: AppEncryptionDeclarationCreateRequestDataRelationshipsApp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': AlternativeDistributionKeyCreateRequestDataRelationshipsAppDataToJSON(value.data),
    };
}

