/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AlternativeDistributionKeyCreateRequestDataRelationshipsAppData } from './AlternativeDistributionKeyCreateRequestDataRelationshipsAppData';
import {
    AlternativeDistributionKeyCreateRequestDataRelationshipsAppDataFromJSON,
    AlternativeDistributionKeyCreateRequestDataRelationshipsAppDataFromJSONTyped,
    AlternativeDistributionKeyCreateRequestDataRelationshipsAppDataToJSON,
} from './AlternativeDistributionKeyCreateRequestDataRelationshipsAppData';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
} from './RelationshipLinks';

/**
 * 
 * @export
 * @interface AppEncryptionDeclarationRelationshipsApp
 */
export interface AppEncryptionDeclarationRelationshipsApp {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof AppEncryptionDeclarationRelationshipsApp
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {AlternativeDistributionKeyCreateRequestDataRelationshipsAppData}
     * @memberof AppEncryptionDeclarationRelationshipsApp
     */
    data?: AlternativeDistributionKeyCreateRequestDataRelationshipsAppData;
}

/**
 * Check if a given object implements the AppEncryptionDeclarationRelationshipsApp interface.
 */
export function instanceOfAppEncryptionDeclarationRelationshipsApp(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppEncryptionDeclarationRelationshipsAppFromJSON(json: any): AppEncryptionDeclarationRelationshipsApp {
    return AppEncryptionDeclarationRelationshipsAppFromJSONTyped(json, false);
}

export function AppEncryptionDeclarationRelationshipsAppFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppEncryptionDeclarationRelationshipsApp {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : RelationshipLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AlternativeDistributionKeyCreateRequestDataRelationshipsAppDataFromJSON(json['data']),
    };
}

export function AppEncryptionDeclarationRelationshipsAppToJSON(value?: AppEncryptionDeclarationRelationshipsApp | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': RelationshipLinksToJSON(value.links),
        'data': AlternativeDistributionKeyCreateRequestDataRelationshipsAppDataToJSON(value.data),
    };
}

