/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppEncryptionDeclarationCreateRequestDataAttributes } from './AppEncryptionDeclarationCreateRequestDataAttributes';
import {
    AppEncryptionDeclarationCreateRequestDataAttributesFromJSON,
    AppEncryptionDeclarationCreateRequestDataAttributesFromJSONTyped,
    AppEncryptionDeclarationCreateRequestDataAttributesToJSON,
} from './AppEncryptionDeclarationCreateRequestDataAttributes';
import type { AppEncryptionDeclarationCreateRequestDataRelationships } from './AppEncryptionDeclarationCreateRequestDataRelationships';
import {
    AppEncryptionDeclarationCreateRequestDataRelationshipsFromJSON,
    AppEncryptionDeclarationCreateRequestDataRelationshipsFromJSONTyped,
    AppEncryptionDeclarationCreateRequestDataRelationshipsToJSON,
} from './AppEncryptionDeclarationCreateRequestDataRelationships';

/**
 * 
 * @export
 * @interface AppEncryptionDeclarationCreateRequestData
 */
export interface AppEncryptionDeclarationCreateRequestData {
    /**
     * 
     * @type {string}
     * @memberof AppEncryptionDeclarationCreateRequestData
     */
    type: AppEncryptionDeclarationCreateRequestDataTypeEnum;
    /**
     * 
     * @type {AppEncryptionDeclarationCreateRequestDataAttributes}
     * @memberof AppEncryptionDeclarationCreateRequestData
     */
    attributes: AppEncryptionDeclarationCreateRequestDataAttributes;
    /**
     * 
     * @type {AppEncryptionDeclarationCreateRequestDataRelationships}
     * @memberof AppEncryptionDeclarationCreateRequestData
     */
    relationships: AppEncryptionDeclarationCreateRequestDataRelationships;
}


/**
 * @export
 */
export const AppEncryptionDeclarationCreateRequestDataTypeEnum = {
    AppEncryptionDeclarations: 'appEncryptionDeclarations'
} as const;
export type AppEncryptionDeclarationCreateRequestDataTypeEnum = typeof AppEncryptionDeclarationCreateRequestDataTypeEnum[keyof typeof AppEncryptionDeclarationCreateRequestDataTypeEnum];


/**
 * Check if a given object implements the AppEncryptionDeclarationCreateRequestData interface.
 */
export function instanceOfAppEncryptionDeclarationCreateRequestData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "relationships" in value;

    return isInstance;
}

export function AppEncryptionDeclarationCreateRequestDataFromJSON(json: any): AppEncryptionDeclarationCreateRequestData {
    return AppEncryptionDeclarationCreateRequestDataFromJSONTyped(json, false);
}

export function AppEncryptionDeclarationCreateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppEncryptionDeclarationCreateRequestData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': AppEncryptionDeclarationCreateRequestDataAttributesFromJSON(json['attributes']),
        'relationships': AppEncryptionDeclarationCreateRequestDataRelationshipsFromJSON(json['relationships']),
    };
}

export function AppEncryptionDeclarationCreateRequestDataToJSON(value?: AppEncryptionDeclarationCreateRequestData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'attributes': AppEncryptionDeclarationCreateRequestDataAttributesToJSON(value.attributes),
        'relationships': AppEncryptionDeclarationCreateRequestDataRelationshipsToJSON(value.relationships),
    };
}

