/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppRelationshipsPromotedPurchasesDataInner } from './AppRelationshipsPromotedPurchasesDataInner';
import {
    AppRelationshipsPromotedPurchasesDataInnerFromJSON,
    AppRelationshipsPromotedPurchasesDataInnerFromJSONTyped,
    AppRelationshipsPromotedPurchasesDataInnerToJSON,
} from './AppRelationshipsPromotedPurchasesDataInner';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
} from './RelationshipLinks';

/**
 * 
 * @export
 * @interface AppRelationshipsPromotedPurchases
 */
export interface AppRelationshipsPromotedPurchases {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof AppRelationshipsPromotedPurchases
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof AppRelationshipsPromotedPurchases
     */
    meta?: PagingInformation;
    /**
     * 
     * @type {Array<AppRelationshipsPromotedPurchasesDataInner>}
     * @memberof AppRelationshipsPromotedPurchases
     */
    data?: Array<AppRelationshipsPromotedPurchasesDataInner>;
}

/**
 * Check if a given object implements the AppRelationshipsPromotedPurchases interface.
 */
export function instanceOfAppRelationshipsPromotedPurchases(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppRelationshipsPromotedPurchasesFromJSON(json: any): AppRelationshipsPromotedPurchases {
    return AppRelationshipsPromotedPurchasesFromJSONTyped(json, false);
}

export function AppRelationshipsPromotedPurchasesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppRelationshipsPromotedPurchases {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : RelationshipLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(AppRelationshipsPromotedPurchasesDataInnerFromJSON)),
    };
}

export function AppRelationshipsPromotedPurchasesToJSON(value?: AppRelationshipsPromotedPurchases | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': RelationshipLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(AppRelationshipsPromotedPurchasesDataInnerToJSON)),
    };
}

