/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppStoreVersionRelationshipsGameCenterAppVersionData } from './AppStoreVersionRelationshipsGameCenterAppVersionData';
import {
    AppStoreVersionRelationshipsGameCenterAppVersionDataFromJSON,
    AppStoreVersionRelationshipsGameCenterAppVersionDataFromJSONTyped,
    AppStoreVersionRelationshipsGameCenterAppVersionDataToJSON,
} from './AppStoreVersionRelationshipsGameCenterAppVersionData';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
} from './RelationshipLinks';

/**
 * 
 * @export
 * @interface AppStoreVersionRelationshipsGameCenterAppVersion
 */
export interface AppStoreVersionRelationshipsGameCenterAppVersion {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof AppStoreVersionRelationshipsGameCenterAppVersion
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {AppStoreVersionRelationshipsGameCenterAppVersionData}
     * @memberof AppStoreVersionRelationshipsGameCenterAppVersion
     */
    data?: AppStoreVersionRelationshipsGameCenterAppVersionData;
}

/**
 * Check if a given object implements the AppStoreVersionRelationshipsGameCenterAppVersion interface.
 */
export function instanceOfAppStoreVersionRelationshipsGameCenterAppVersion(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppStoreVersionRelationshipsGameCenterAppVersionFromJSON(json: any): AppStoreVersionRelationshipsGameCenterAppVersion {
    return AppStoreVersionRelationshipsGameCenterAppVersionFromJSONTyped(json, false);
}

export function AppStoreVersionRelationshipsGameCenterAppVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreVersionRelationshipsGameCenterAppVersion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : RelationshipLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : AppStoreVersionRelationshipsGameCenterAppVersionDataFromJSON(json['data']),
    };
}

export function AppStoreVersionRelationshipsGameCenterAppVersionToJSON(value?: AppStoreVersionRelationshipsGameCenterAppVersion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': RelationshipLinksToJSON(value.links),
        'data': AppStoreVersionRelationshipsGameCenterAppVersionDataToJSON(value.data),
    };
}

