/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperiment } from './AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperiment';
import {
    AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperimentFromJSON,
    AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperimentFromJSONTyped,
    AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperimentToJSON,
} from './AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperiment';

/**
 * 
 * @export
 * @interface AppStoreVersionExperimentTreatmentCreateRequestDataRelationships
 */
export interface AppStoreVersionExperimentTreatmentCreateRequestDataRelationships {
    /**
     * 
     * @type {AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperiment}
     * @memberof AppStoreVersionExperimentTreatmentCreateRequestDataRelationships
     */
    appStoreVersionExperiment?: AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperiment;
    /**
     * 
     * @type {AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperiment}
     * @memberof AppStoreVersionExperimentTreatmentCreateRequestDataRelationships
     */
    appStoreVersionExperimentV2?: AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperiment;
}

/**
 * Check if a given object implements the AppStoreVersionExperimentTreatmentCreateRequestDataRelationships interface.
 */
export function instanceOfAppStoreVersionExperimentTreatmentCreateRequestDataRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AppStoreVersionExperimentTreatmentCreateRequestDataRelationshipsFromJSON(json: any): AppStoreVersionExperimentTreatmentCreateRequestDataRelationships {
    return AppStoreVersionExperimentTreatmentCreateRequestDataRelationshipsFromJSONTyped(json, false);
}

export function AppStoreVersionExperimentTreatmentCreateRequestDataRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreVersionExperimentTreatmentCreateRequestDataRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'appStoreVersionExperiment': !exists(json, 'appStoreVersionExperiment') ? undefined : AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperimentFromJSON(json['appStoreVersionExperiment']),
        'appStoreVersionExperimentV2': !exists(json, 'appStoreVersionExperimentV2') ? undefined : AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperimentFromJSON(json['appStoreVersionExperimentV2']),
    };
}

export function AppStoreVersionExperimentTreatmentCreateRequestDataRelationshipsToJSON(value?: AppStoreVersionExperimentTreatmentCreateRequestDataRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'appStoreVersionExperiment': AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperimentToJSON(value.appStoreVersionExperiment),
        'appStoreVersionExperimentV2': AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperimentToJSON(value.appStoreVersionExperimentV2),
    };
}

