/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BetaRecruitmentCriterionCreateRequestDataRelationshipsBetaGroup } from './BetaRecruitmentCriterionCreateRequestDataRelationshipsBetaGroup';
import {
    BetaRecruitmentCriterionCreateRequestDataRelationshipsBetaGroupFromJSON,
    BetaRecruitmentCriterionCreateRequestDataRelationshipsBetaGroupFromJSONTyped,
    BetaRecruitmentCriterionCreateRequestDataRelationshipsBetaGroupToJSON,
} from './BetaRecruitmentCriterionCreateRequestDataRelationshipsBetaGroup';

/**
 * 
 * @export
 * @interface BetaRecruitmentCriterionCreateRequestDataRelationships
 */
export interface BetaRecruitmentCriterionCreateRequestDataRelationships {
    /**
     * 
     * @type {BetaRecruitmentCriterionCreateRequestDataRelationshipsBetaGroup}
     * @memberof BetaRecruitmentCriterionCreateRequestDataRelationships
     */
    betaGroup: BetaRecruitmentCriterionCreateRequestDataRelationshipsBetaGroup;
}

/**
 * Check if a given object implements the BetaRecruitmentCriterionCreateRequestDataRelationships interface.
 */
export function instanceOfBetaRecruitmentCriterionCreateRequestDataRelationships(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "betaGroup" in value;

    return isInstance;
}

export function BetaRecruitmentCriterionCreateRequestDataRelationshipsFromJSON(json: any): BetaRecruitmentCriterionCreateRequestDataRelationships {
    return BetaRecruitmentCriterionCreateRequestDataRelationshipsFromJSONTyped(json, false);
}

export function BetaRecruitmentCriterionCreateRequestDataRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaRecruitmentCriterionCreateRequestDataRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'betaGroup': BetaRecruitmentCriterionCreateRequestDataRelationshipsBetaGroupFromJSON(json['betaGroup']),
    };
}

export function BetaRecruitmentCriterionCreateRequestDataRelationshipsToJSON(value?: BetaRecruitmentCriterionCreateRequestDataRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'betaGroup': BetaRecruitmentCriterionCreateRequestDataRelationshipsBetaGroupToJSON(value.betaGroup),
    };
}

