/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BetaRecruitmentCriterionOptionAttributes } from './BetaRecruitmentCriterionOptionAttributes';
import {
    BetaRecruitmentCriterionOptionAttributesFromJSON,
    BetaRecruitmentCriterionOptionAttributesFromJSONTyped,
    BetaRecruitmentCriterionOptionAttributesToJSON,
} from './BetaRecruitmentCriterionOptionAttributes';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
} from './ResourceLinks';

/**
 * 
 * @export
 * @interface BetaRecruitmentCriterionOption
 */
export interface BetaRecruitmentCriterionOption {
    /**
     * 
     * @type {string}
     * @memberof BetaRecruitmentCriterionOption
     */
    type: BetaRecruitmentCriterionOptionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof BetaRecruitmentCriterionOption
     */
    id: string;
    /**
     * 
     * @type {BetaRecruitmentCriterionOptionAttributes}
     * @memberof BetaRecruitmentCriterionOption
     */
    attributes?: BetaRecruitmentCriterionOptionAttributes;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof BetaRecruitmentCriterionOption
     */
    links?: ResourceLinks;
}


/**
 * @export
 */
export const BetaRecruitmentCriterionOptionTypeEnum = {
    BetaRecruitmentCriterionOptions: 'betaRecruitmentCriterionOptions'
} as const;
export type BetaRecruitmentCriterionOptionTypeEnum = typeof BetaRecruitmentCriterionOptionTypeEnum[keyof typeof BetaRecruitmentCriterionOptionTypeEnum];


/**
 * Check if a given object implements the BetaRecruitmentCriterionOption interface.
 */
export function instanceOfBetaRecruitmentCriterionOption(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function BetaRecruitmentCriterionOptionFromJSON(json: any): BetaRecruitmentCriterionOption {
    return BetaRecruitmentCriterionOptionFromJSONTyped(json, false);
}

export function BetaRecruitmentCriterionOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaRecruitmentCriterionOption {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': !exists(json, 'attributes') ? undefined : BetaRecruitmentCriterionOptionAttributesFromJSON(json['attributes']),
        'links': !exists(json, 'links') ? undefined : ResourceLinksFromJSON(json['links']),
    };
}

export function BetaRecruitmentCriterionOptionToJSON(value?: BetaRecruitmentCriterionOption | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': BetaRecruitmentCriterionOptionAttributesToJSON(value.attributes),
        'links': ResourceLinksToJSON(value.links),
    };
}

