/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BetaRecruitmentCriterionAttributes } from './BetaRecruitmentCriterionAttributes';
import {
    BetaRecruitmentCriterionAttributesFromJSON,
    BetaRecruitmentCriterionAttributesFromJSONTyped,
    BetaRecruitmentCriterionAttributesToJSON,
} from './BetaRecruitmentCriterionAttributes';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
} from './ResourceLinks';

/**
 * 
 * @export
 * @interface BetaRecruitmentCriterion
 */
export interface BetaRecruitmentCriterion {
    /**
     * 
     * @type {string}
     * @memberof BetaRecruitmentCriterion
     */
    type: BetaRecruitmentCriterionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof BetaRecruitmentCriterion
     */
    id: string;
    /**
     * 
     * @type {BetaRecruitmentCriterionAttributes}
     * @memberof BetaRecruitmentCriterion
     */
    attributes?: BetaRecruitmentCriterionAttributes;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof BetaRecruitmentCriterion
     */
    links?: ResourceLinks;
}


/**
 * @export
 */
export const BetaRecruitmentCriterionTypeEnum = {
    BetaRecruitmentCriteria: 'betaRecruitmentCriteria'
} as const;
export type BetaRecruitmentCriterionTypeEnum = typeof BetaRecruitmentCriterionTypeEnum[keyof typeof BetaRecruitmentCriterionTypeEnum];


/**
 * Check if a given object implements the BetaRecruitmentCriterion interface.
 */
export function instanceOfBetaRecruitmentCriterion(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function BetaRecruitmentCriterionFromJSON(json: any): BetaRecruitmentCriterion {
    return BetaRecruitmentCriterionFromJSONTyped(json, false);
}

export function BetaRecruitmentCriterionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaRecruitmentCriterion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': !exists(json, 'attributes') ? undefined : BetaRecruitmentCriterionAttributesFromJSON(json['attributes']),
        'links': !exists(json, 'links') ? undefined : ResourceLinksFromJSON(json['links']),
    };
}

export function BetaRecruitmentCriterionToJSON(value?: BetaRecruitmentCriterion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': BetaRecruitmentCriterionAttributesToJSON(value.attributes),
        'links': ResourceLinksToJSON(value.links),
    };
}

