/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BetaGroupRelationshipsBetaRecruitmentCriteriaData
 */
export interface BetaGroupRelationshipsBetaRecruitmentCriteriaData {
    /**
     * 
     * @type {string}
     * @memberof BetaGroupRelationshipsBetaRecruitmentCriteriaData
     */
    type: BetaGroupRelationshipsBetaRecruitmentCriteriaDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof BetaGroupRelationshipsBetaRecruitmentCriteriaData
     */
    id: string;
}


/**
 * @export
 */
export const BetaGroupRelationshipsBetaRecruitmentCriteriaDataTypeEnum = {
    BetaRecruitmentCriteria: 'betaRecruitmentCriteria'
} as const;
export type BetaGroupRelationshipsBetaRecruitmentCriteriaDataTypeEnum = typeof BetaGroupRelationshipsBetaRecruitmentCriteriaDataTypeEnum[keyof typeof BetaGroupRelationshipsBetaRecruitmentCriteriaDataTypeEnum];


/**
 * Check if a given object implements the BetaGroupRelationshipsBetaRecruitmentCriteriaData interface.
 */
export function instanceOfBetaGroupRelationshipsBetaRecruitmentCriteriaData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function BetaGroupRelationshipsBetaRecruitmentCriteriaDataFromJSON(json: any): BetaGroupRelationshipsBetaRecruitmentCriteriaData {
    return BetaGroupRelationshipsBetaRecruitmentCriteriaDataFromJSONTyped(json, false);
}

export function BetaGroupRelationshipsBetaRecruitmentCriteriaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaGroupRelationshipsBetaRecruitmentCriteriaData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function BetaGroupRelationshipsBetaRecruitmentCriteriaDataToJSON(value?: BetaGroupRelationshipsBetaRecruitmentCriteriaData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
    };
}

