/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BetaPublicLinkUsagesV1MetricResponseDataInnerDataPoints } from './BetaPublicLinkUsagesV1MetricResponseDataInnerDataPoints';
import {
    BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsFromJSON,
    BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsFromJSONTyped,
    BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsToJSON,
} from './BetaPublicLinkUsagesV1MetricResponseDataInnerDataPoints';

/**
 * 
 * @export
 * @interface BetaPublicLinkUsagesV1MetricResponseDataInner
 */
export interface BetaPublicLinkUsagesV1MetricResponseDataInner {
    /**
     * 
     * @type {BetaPublicLinkUsagesV1MetricResponseDataInnerDataPoints}
     * @memberof BetaPublicLinkUsagesV1MetricResponseDataInner
     */
    dataPoints?: BetaPublicLinkUsagesV1MetricResponseDataInnerDataPoints;
}

/**
 * Check if a given object implements the BetaPublicLinkUsagesV1MetricResponseDataInner interface.
 */
export function instanceOfBetaPublicLinkUsagesV1MetricResponseDataInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BetaPublicLinkUsagesV1MetricResponseDataInnerFromJSON(json: any): BetaPublicLinkUsagesV1MetricResponseDataInner {
    return BetaPublicLinkUsagesV1MetricResponseDataInnerFromJSONTyped(json, false);
}

export function BetaPublicLinkUsagesV1MetricResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaPublicLinkUsagesV1MetricResponseDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dataPoints': !exists(json, 'dataPoints') ? undefined : BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsFromJSON(json['dataPoints']),
    };
}

export function BetaPublicLinkUsagesV1MetricResponseDataInnerToJSON(value?: BetaPublicLinkUsagesV1MetricResponseDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dataPoints': BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsToJSON(value.dataPoints),
    };
}

