/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues
 */
export interface BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues {
    /**
     * 
     * @type {number}
     * @memberof BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues
     */
    viewCount?: number;
    /**
     * 
     * @type {number}
     * @memberof BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues
     */
    acceptedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues
     */
    didNotAcceptCount?: number;
    /**
     * 
     * @type {number}
     * @memberof BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues
     */
    didNotMeetCriteriaCount?: number;
    /**
     * 
     * @type {number}
     * @memberof BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues
     */
    notRelevantRatio?: number;
    /**
     * 
     * @type {number}
     * @memberof BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues
     */
    notClearRatio?: number;
    /**
     * 
     * @type {number}
     * @memberof BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues
     */
    notInterestingRatio?: number;
}

/**
 * Check if a given object implements the BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues interface.
 */
export function instanceOfBetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValuesFromJSON(json: any): BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues {
    return BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValuesFromJSONTyped(json, false);
}

export function BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'viewCount': !exists(json, 'viewCount') ? undefined : json['viewCount'],
        'acceptedCount': !exists(json, 'acceptedCount') ? undefined : json['acceptedCount'],
        'didNotAcceptCount': !exists(json, 'didNotAcceptCount') ? undefined : json['didNotAcceptCount'],
        'didNotMeetCriteriaCount': !exists(json, 'didNotMeetCriteriaCount') ? undefined : json['didNotMeetCriteriaCount'],
        'notRelevantRatio': !exists(json, 'notRelevantRatio') ? undefined : json['notRelevantRatio'],
        'notClearRatio': !exists(json, 'notClearRatio') ? undefined : json['notClearRatio'],
        'notInterestingRatio': !exists(json, 'notInterestingRatio') ? undefined : json['notInterestingRatio'],
    };
}

export function BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValuesToJSON(value?: BetaPublicLinkUsagesV1MetricResponseDataInnerDataPointsValues | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'viewCount': value.viewCount,
        'acceptedCount': value.acceptedCount,
        'didNotAcceptCount': value.didNotAcceptCount,
        'didNotMeetCriteriaCount': value.didNotMeetCriteriaCount,
        'notRelevantRatio': value.notRelevantRatio,
        'notClearRatio': value.notClearRatio,
        'notInterestingRatio': value.notInterestingRatio,
    };
}

