/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BuildBundleRelationshipsAppClipDomainCacheStatusData } from './BuildBundleRelationshipsAppClipDomainCacheStatusData';
import {
    BuildBundleRelationshipsAppClipDomainCacheStatusDataFromJSON,
    BuildBundleRelationshipsAppClipDomainCacheStatusDataFromJSONTyped,
    BuildBundleRelationshipsAppClipDomainCacheStatusDataToJSON,
} from './BuildBundleRelationshipsAppClipDomainCacheStatusData';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
} from './RelationshipLinks';

/**
 * 
 * @export
 * @interface BuildBundleRelationshipsAppClipDomainCacheStatus
 */
export interface BuildBundleRelationshipsAppClipDomainCacheStatus {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof BuildBundleRelationshipsAppClipDomainCacheStatus
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {BuildBundleRelationshipsAppClipDomainCacheStatusData}
     * @memberof BuildBundleRelationshipsAppClipDomainCacheStatus
     */
    data?: BuildBundleRelationshipsAppClipDomainCacheStatusData;
}

/**
 * Check if a given object implements the BuildBundleRelationshipsAppClipDomainCacheStatus interface.
 */
export function instanceOfBuildBundleRelationshipsAppClipDomainCacheStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BuildBundleRelationshipsAppClipDomainCacheStatusFromJSON(json: any): BuildBundleRelationshipsAppClipDomainCacheStatus {
    return BuildBundleRelationshipsAppClipDomainCacheStatusFromJSONTyped(json, false);
}

export function BuildBundleRelationshipsAppClipDomainCacheStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildBundleRelationshipsAppClipDomainCacheStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : RelationshipLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : BuildBundleRelationshipsAppClipDomainCacheStatusDataFromJSON(json['data']),
    };
}

export function BuildBundleRelationshipsAppClipDomainCacheStatusToJSON(value?: BuildBundleRelationshipsAppClipDomainCacheStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': RelationshipLinksToJSON(value.links),
        'data': BuildBundleRelationshipsAppClipDomainCacheStatusDataToJSON(value.data),
    };
}

