/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CertificateUpdateRequestDataAttributes
 */
export interface CertificateUpdateRequestDataAttributes {
    /**
     * 
     * @type {boolean}
     * @memberof CertificateUpdateRequestDataAttributes
     */
    activated?: boolean;
}

/**
 * Check if a given object implements the CertificateUpdateRequestDataAttributes interface.
 */
export function instanceOfCertificateUpdateRequestDataAttributes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CertificateUpdateRequestDataAttributesFromJSON(json: any): CertificateUpdateRequestDataAttributes {
    return CertificateUpdateRequestDataAttributesFromJSONTyped(json, false);
}

export function CertificateUpdateRequestDataAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CertificateUpdateRequestDataAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'activated': !exists(json, 'activated') ? undefined : json['activated'],
    };
}

export function CertificateUpdateRequestDataAttributesToJSON(value?: CertificateUpdateRequestDataAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'activated': value.activated,
    };
}

