/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AnalyticsReportInstanceRelationshipsSegments } from './AnalyticsReportInstanceRelationshipsSegments';
import {
    AnalyticsReportInstanceRelationshipsSegmentsFromJSON,
    AnalyticsReportInstanceRelationshipsSegmentsFromJSONTyped,
    AnalyticsReportInstanceRelationshipsSegmentsToJSON,
} from './AnalyticsReportInstanceRelationshipsSegments';
import type { CiBuildActionRelationshipsBuildRun } from './CiBuildActionRelationshipsBuildRun';
import {
    CiBuildActionRelationshipsBuildRunFromJSON,
    CiBuildActionRelationshipsBuildRunFromJSONTyped,
    CiBuildActionRelationshipsBuildRunToJSON,
} from './CiBuildActionRelationshipsBuildRun';

/**
 * 
 * @export
 * @interface CiBuildActionRelationships
 */
export interface CiBuildActionRelationships {
    /**
     * 
     * @type {CiBuildActionRelationshipsBuildRun}
     * @memberof CiBuildActionRelationships
     */
    buildRun?: CiBuildActionRelationshipsBuildRun;
    /**
     * 
     * @type {AnalyticsReportInstanceRelationshipsSegments}
     * @memberof CiBuildActionRelationships
     */
    artifacts?: AnalyticsReportInstanceRelationshipsSegments;
    /**
     * 
     * @type {AnalyticsReportInstanceRelationshipsSegments}
     * @memberof CiBuildActionRelationships
     */
    issues?: AnalyticsReportInstanceRelationshipsSegments;
    /**
     * 
     * @type {AnalyticsReportInstanceRelationshipsSegments}
     * @memberof CiBuildActionRelationships
     */
    testResults?: AnalyticsReportInstanceRelationshipsSegments;
}

/**
 * Check if a given object implements the CiBuildActionRelationships interface.
 */
export function instanceOfCiBuildActionRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CiBuildActionRelationshipsFromJSON(json: any): CiBuildActionRelationships {
    return CiBuildActionRelationshipsFromJSONTyped(json, false);
}

export function CiBuildActionRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CiBuildActionRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buildRun': !exists(json, 'buildRun') ? undefined : CiBuildActionRelationshipsBuildRunFromJSON(json['buildRun']),
        'artifacts': !exists(json, 'artifacts') ? undefined : AnalyticsReportInstanceRelationshipsSegmentsFromJSON(json['artifacts']),
        'issues': !exists(json, 'issues') ? undefined : AnalyticsReportInstanceRelationshipsSegmentsFromJSON(json['issues']),
        'testResults': !exists(json, 'testResults') ? undefined : AnalyticsReportInstanceRelationshipsSegmentsFromJSON(json['testResults']),
    };
}

export function CiBuildActionRelationshipsToJSON(value?: CiBuildActionRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buildRun': CiBuildActionRelationshipsBuildRunToJSON(value.buildRun),
        'artifacts': AnalyticsReportInstanceRelationshipsSegmentsToJSON(value.artifacts),
        'issues': AnalyticsReportInstanceRelationshipsSegmentsToJSON(value.issues),
        'testResults': AnalyticsReportInstanceRelationshipsSegmentsToJSON(value.testResults),
    };
}

