/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CiMacOsVersionRelationshipsXcodeVersionsDataInner } from './CiMacOsVersionRelationshipsXcodeVersionsDataInner';
import {
    CiMacOsVersionRelationshipsXcodeVersionsDataInnerFromJSON,
    CiMacOsVersionRelationshipsXcodeVersionsDataInnerFromJSONTyped,
    CiMacOsVersionRelationshipsXcodeVersionsDataInnerToJSON,
} from './CiMacOsVersionRelationshipsXcodeVersionsDataInner';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
} from './RelationshipLinks';

/**
 * 
 * @export
 * @interface CiMacOsVersionRelationshipsXcodeVersions
 */
export interface CiMacOsVersionRelationshipsXcodeVersions {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof CiMacOsVersionRelationshipsXcodeVersions
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof CiMacOsVersionRelationshipsXcodeVersions
     */
    meta?: PagingInformation;
    /**
     * 
     * @type {Array<CiMacOsVersionRelationshipsXcodeVersionsDataInner>}
     * @memberof CiMacOsVersionRelationshipsXcodeVersions
     */
    data?: Array<CiMacOsVersionRelationshipsXcodeVersionsDataInner>;
}

/**
 * Check if a given object implements the CiMacOsVersionRelationshipsXcodeVersions interface.
 */
export function instanceOfCiMacOsVersionRelationshipsXcodeVersions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CiMacOsVersionRelationshipsXcodeVersionsFromJSON(json: any): CiMacOsVersionRelationshipsXcodeVersions {
    return CiMacOsVersionRelationshipsXcodeVersionsFromJSONTyped(json, false);
}

export function CiMacOsVersionRelationshipsXcodeVersionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CiMacOsVersionRelationshipsXcodeVersions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : RelationshipLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(CiMacOsVersionRelationshipsXcodeVersionsDataInnerFromJSON)),
    };
}

export function CiMacOsVersionRelationshipsXcodeVersionsToJSON(value?: CiMacOsVersionRelationshipsXcodeVersions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': RelationshipLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(CiMacOsVersionRelationshipsXcodeVersionsDataInnerToJSON)),
    };
}

