/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AnalyticsReportInstanceRelationshipsSegments } from './AnalyticsReportInstanceRelationshipsSegments';
import {
    AnalyticsReportInstanceRelationshipsSegmentsFromJSON,
    AnalyticsReportInstanceRelationshipsSegmentsFromJSONTyped,
    AnalyticsReportInstanceRelationshipsSegmentsToJSON,
} from './AnalyticsReportInstanceRelationshipsSegments';
import type { BetaAppLocalizationRelationshipsApp } from './BetaAppLocalizationRelationshipsApp';
import {
    BetaAppLocalizationRelationshipsAppFromJSON,
    BetaAppLocalizationRelationshipsAppFromJSONTyped,
    BetaAppLocalizationRelationshipsAppToJSON,
} from './BetaAppLocalizationRelationshipsApp';
import type { CiProductRelationshipsBundleId } from './CiProductRelationshipsBundleId';
import {
    CiProductRelationshipsBundleIdFromJSON,
    CiProductRelationshipsBundleIdFromJSONTyped,
    CiProductRelationshipsBundleIdToJSON,
} from './CiProductRelationshipsBundleId';
import type { CiProductRelationshipsPrimaryRepositories } from './CiProductRelationshipsPrimaryRepositories';
import {
    CiProductRelationshipsPrimaryRepositoriesFromJSON,
    CiProductRelationshipsPrimaryRepositoriesFromJSONTyped,
    CiProductRelationshipsPrimaryRepositoriesToJSON,
} from './CiProductRelationshipsPrimaryRepositories';

/**
 * 
 * @export
 * @interface CiProductRelationships
 */
export interface CiProductRelationships {
    /**
     * 
     * @type {BetaAppLocalizationRelationshipsApp}
     * @memberof CiProductRelationships
     */
    app?: BetaAppLocalizationRelationshipsApp;
    /**
     * 
     * @type {CiProductRelationshipsBundleId}
     * @memberof CiProductRelationships
     */
    bundleId?: CiProductRelationshipsBundleId;
    /**
     * 
     * @type {AnalyticsReportInstanceRelationshipsSegments}
     * @memberof CiProductRelationships
     */
    workflows?: AnalyticsReportInstanceRelationshipsSegments;
    /**
     * 
     * @type {CiProductRelationshipsPrimaryRepositories}
     * @memberof CiProductRelationships
     */
    primaryRepositories?: CiProductRelationshipsPrimaryRepositories;
    /**
     * 
     * @type {AnalyticsReportInstanceRelationshipsSegments}
     * @memberof CiProductRelationships
     */
    additionalRepositories?: AnalyticsReportInstanceRelationshipsSegments;
    /**
     * 
     * @type {AnalyticsReportInstanceRelationshipsSegments}
     * @memberof CiProductRelationships
     */
    buildRuns?: AnalyticsReportInstanceRelationshipsSegments;
}

/**
 * Check if a given object implements the CiProductRelationships interface.
 */
export function instanceOfCiProductRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CiProductRelationshipsFromJSON(json: any): CiProductRelationships {
    return CiProductRelationshipsFromJSONTyped(json, false);
}

export function CiProductRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CiProductRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'app': !exists(json, 'app') ? undefined : BetaAppLocalizationRelationshipsAppFromJSON(json['app']),
        'bundleId': !exists(json, 'bundleId') ? undefined : CiProductRelationshipsBundleIdFromJSON(json['bundleId']),
        'workflows': !exists(json, 'workflows') ? undefined : AnalyticsReportInstanceRelationshipsSegmentsFromJSON(json['workflows']),
        'primaryRepositories': !exists(json, 'primaryRepositories') ? undefined : CiProductRelationshipsPrimaryRepositoriesFromJSON(json['primaryRepositories']),
        'additionalRepositories': !exists(json, 'additionalRepositories') ? undefined : AnalyticsReportInstanceRelationshipsSegmentsFromJSON(json['additionalRepositories']),
        'buildRuns': !exists(json, 'buildRuns') ? undefined : AnalyticsReportInstanceRelationshipsSegmentsFromJSON(json['buildRuns']),
    };
}

export function CiProductRelationshipsToJSON(value?: CiProductRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'app': BetaAppLocalizationRelationshipsAppToJSON(value.app),
        'bundleId': CiProductRelationshipsBundleIdToJSON(value.bundleId),
        'workflows': AnalyticsReportInstanceRelationshipsSegmentsToJSON(value.workflows),
        'primaryRepositories': CiProductRelationshipsPrimaryRepositoriesToJSON(value.primaryRepositories),
        'additionalRepositories': AnalyticsReportInstanceRelationshipsSegmentsToJSON(value.additionalRepositories),
        'buildRuns': AnalyticsReportInstanceRelationshipsSegmentsToJSON(value.buildRuns),
    };
}

