/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DeviceFamily = {
    Iphone: 'IPHONE',
    Ipad: 'IPAD',
    AppleTv: 'APPLE_TV',
    AppleWatch: 'APPLE_WATCH',
    Mac: 'MAC',
    Vision: 'VISION'
} as const;
export type DeviceFamily = typeof DeviceFamily[keyof typeof DeviceFamily];


export function DeviceFamilyFromJSON(json: any): DeviceFamily {
    return DeviceFamilyFromJSONTyped(json, false);
}

export function DeviceFamilyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceFamily {
    return json as DeviceFamily;
}

export function DeviceFamilyToJSON(value?: DeviceFamily | null): any {
    return value as any;
}

