/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageData } from './GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageData';
import {
    GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageDataFromJSON,
    GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageDataFromJSONTyped,
    GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageDataToJSON,
} from './GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageData';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
} from './RelationshipLinks';

/**
 * 
 * @export
 * @interface GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage
 */
export interface GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageData}
     * @memberof GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage
     */
    data?: GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageData;
}

/**
 * Check if a given object implements the GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage interface.
 */
export function instanceOfGameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageFromJSON(json: any): GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage {
    return GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageFromJSONTyped(json, false);
}

export function GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : RelationshipLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageDataFromJSON(json['data']),
    };
}

export function GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageToJSON(value?: GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': RelationshipLinksToJSON(value.links),
        'data': GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSetImageDataToJSON(value.data),
    };
}

