/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultLinks } from './GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultLinks';
import {
    GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultLinksFromJSON,
    GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultLinksFromJSONTyped,
    GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultLinksToJSON,
} from './GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultLinks';

/**
 * 
 * @export
 * @interface GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResult
 */
export interface GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResult {
    /**
     * 
     * @type {GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultLinks}
     * @memberof GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResult
     */
    links?: GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultLinks;
    /**
     * 
     * @type {string}
     * @memberof GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResult
     */
    data?: GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultDataEnum;
}


/**
 * @export
 */
export const GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultDataEnum = {
    Matched: 'MATCHED',
    Canceled: 'CANCELED',
    Expired: 'EXPIRED'
} as const;
export type GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultDataEnum = typeof GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultDataEnum[keyof typeof GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultDataEnum];


/**
 * Check if a given object implements the GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResult interface.
 */
export function instanceOfGameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultFromJSON(json: any): GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResult {
    return GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultFromJSONTyped(json, false);
}

export function GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultToJSON(value?: GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': GameCenterMatchmakingAppRequestsV1MetricResponseDataInnerDimensionsResultLinksToJSON(value.links),
        'data': value.data,
    };
}

