/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner } from './GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner';
import {
    GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerFromJSON,
    GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerFromJSONTyped,
    GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerToJSON,
} from './GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
} from './RelationshipLinks';

/**
 * 
 * @export
 * @interface GameCenterLeaderboardRelationshipsGroupLeaderboard
 */
export interface GameCenterLeaderboardRelationshipsGroupLeaderboard {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof GameCenterLeaderboardRelationshipsGroupLeaderboard
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner}
     * @memberof GameCenterLeaderboardRelationshipsGroupLeaderboard
     */
    data?: GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner;
}

/**
 * Check if a given object implements the GameCenterLeaderboardRelationshipsGroupLeaderboard interface.
 */
export function instanceOfGameCenterLeaderboardRelationshipsGroupLeaderboard(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameCenterLeaderboardRelationshipsGroupLeaderboardFromJSON(json: any): GameCenterLeaderboardRelationshipsGroupLeaderboard {
    return GameCenterLeaderboardRelationshipsGroupLeaderboardFromJSONTyped(json, false);
}

export function GameCenterLeaderboardRelationshipsGroupLeaderboardFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterLeaderboardRelationshipsGroupLeaderboard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : RelationshipLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerFromJSON(json['data']),
    };
}

export function GameCenterLeaderboardRelationshipsGroupLeaderboardToJSON(value?: GameCenterLeaderboardRelationshipsGroupLeaderboard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': RelationshipLinksToJSON(value.links),
        'data': GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerToJSON(value.data),
    };
}

