/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GameCenterAchievementReleaseRelationshipsGameCenterAchievement } from './GameCenterAchievementReleaseRelationshipsGameCenterAchievement';
import {
    GameCenterAchievementReleaseRelationshipsGameCenterAchievementFromJSON,
    GameCenterAchievementReleaseRelationshipsGameCenterAchievementFromJSONTyped,
    GameCenterAchievementReleaseRelationshipsGameCenterAchievementToJSON,
} from './GameCenterAchievementReleaseRelationshipsGameCenterAchievement';
import type { GameCenterAchievementReleaseRelationshipsGameCenterDetail } from './GameCenterAchievementReleaseRelationshipsGameCenterDetail';
import {
    GameCenterAchievementReleaseRelationshipsGameCenterDetailFromJSON,
    GameCenterAchievementReleaseRelationshipsGameCenterDetailFromJSONTyped,
    GameCenterAchievementReleaseRelationshipsGameCenterDetailToJSON,
} from './GameCenterAchievementReleaseRelationshipsGameCenterDetail';

/**
 * 
 * @export
 * @interface GameCenterAchievementReleaseRelationships
 */
export interface GameCenterAchievementReleaseRelationships {
    /**
     * 
     * @type {GameCenterAchievementReleaseRelationshipsGameCenterDetail}
     * @memberof GameCenterAchievementReleaseRelationships
     */
    gameCenterDetail?: GameCenterAchievementReleaseRelationshipsGameCenterDetail;
    /**
     * 
     * @type {GameCenterAchievementReleaseRelationshipsGameCenterAchievement}
     * @memberof GameCenterAchievementReleaseRelationships
     */
    gameCenterAchievement?: GameCenterAchievementReleaseRelationshipsGameCenterAchievement;
}

/**
 * Check if a given object implements the GameCenterAchievementReleaseRelationships interface.
 */
export function instanceOfGameCenterAchievementReleaseRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameCenterAchievementReleaseRelationshipsFromJSON(json: any): GameCenterAchievementReleaseRelationships {
    return GameCenterAchievementReleaseRelationshipsFromJSONTyped(json, false);
}

export function GameCenterAchievementReleaseRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterAchievementReleaseRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gameCenterDetail': !exists(json, 'gameCenterDetail') ? undefined : GameCenterAchievementReleaseRelationshipsGameCenterDetailFromJSON(json['gameCenterDetail']),
        'gameCenterAchievement': !exists(json, 'gameCenterAchievement') ? undefined : GameCenterAchievementReleaseRelationshipsGameCenterAchievementFromJSON(json['gameCenterAchievement']),
    };
}

export function GameCenterAchievementReleaseRelationshipsToJSON(value?: GameCenterAchievementReleaseRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gameCenterDetail': GameCenterAchievementReleaseRelationshipsGameCenterDetailToJSON(value.gameCenterDetail),
        'gameCenterAchievement': GameCenterAchievementReleaseRelationshipsGameCenterAchievementToJSON(value.gameCenterAchievement),
    };
}

