/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner } from './GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner';
import {
    GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerFromJSON,
    GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerFromJSONTyped,
    GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerToJSON,
} from './GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner';

/**
 * 
 * @export
 * @interface GameCenterDetailRelationshipsDefaultLeaderboard
 */
export interface GameCenterDetailRelationshipsDefaultLeaderboard {
    /**
     * 
     * @type {GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner}
     * @memberof GameCenterDetailRelationshipsDefaultLeaderboard
     */
    data?: GameCenterDetailRelationshipsGameCenterLeaderboardsDataInner;
}

/**
 * Check if a given object implements the GameCenterDetailRelationshipsDefaultLeaderboard interface.
 */
export function instanceOfGameCenterDetailRelationshipsDefaultLeaderboard(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameCenterDetailRelationshipsDefaultLeaderboardFromJSON(json: any): GameCenterDetailRelationshipsDefaultLeaderboard {
    return GameCenterDetailRelationshipsDefaultLeaderboardFromJSONTyped(json, false);
}

export function GameCenterDetailRelationshipsDefaultLeaderboardFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterDetailRelationshipsDefaultLeaderboard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerFromJSON(json['data']),
    };
}

export function GameCenterDetailRelationshipsDefaultLeaderboardToJSON(value?: GameCenterDetailRelationshipsDefaultLeaderboard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GameCenterDetailRelationshipsGameCenterLeaderboardsDataInnerToJSON(value.data),
    };
}

