/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppRelationshipsGameCenterDetailData } from './AppRelationshipsGameCenterDetailData';
import {
    AppRelationshipsGameCenterDetailDataFromJSON,
    AppRelationshipsGameCenterDetailDataFromJSONTyped,
    AppRelationshipsGameCenterDetailDataToJSON,
} from './AppRelationshipsGameCenterDetailData';

/**
 * 
 * @export
 * @interface GameCenterAchievementReleaseRelationshipsGameCenterDetail
 */
export interface GameCenterAchievementReleaseRelationshipsGameCenterDetail {
    /**
     * 
     * @type {AppRelationshipsGameCenterDetailData}
     * @memberof GameCenterAchievementReleaseRelationshipsGameCenterDetail
     */
    data?: AppRelationshipsGameCenterDetailData;
}

/**
 * Check if a given object implements the GameCenterAchievementReleaseRelationshipsGameCenterDetail interface.
 */
export function instanceOfGameCenterAchievementReleaseRelationshipsGameCenterDetail(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameCenterAchievementReleaseRelationshipsGameCenterDetailFromJSON(json: any): GameCenterAchievementReleaseRelationshipsGameCenterDetail {
    return GameCenterAchievementReleaseRelationshipsGameCenterDetailFromJSONTyped(json, false);
}

export function GameCenterAchievementReleaseRelationshipsGameCenterDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterAchievementReleaseRelationshipsGameCenterDetail {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : AppRelationshipsGameCenterDetailDataFromJSON(json['data']),
    };
}

export function GameCenterAchievementReleaseRelationshipsGameCenterDetailToJSON(value?: GameCenterAchievementReleaseRelationshipsGameCenterDetail | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': AppRelationshipsGameCenterDetailDataToJSON(value.data),
    };
}

