/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationData } from './GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationData';
import {
    GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationDataFromJSON,
    GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationDataFromJSONTyped,
    GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationDataToJSON,
} from './GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationData';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
} from './RelationshipLinks';

/**
 * 
 * @export
 * @interface GameCenterAchievementRelationshipsLocalizations
 */
export interface GameCenterAchievementRelationshipsLocalizations {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof GameCenterAchievementRelationshipsLocalizations
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof GameCenterAchievementRelationshipsLocalizations
     */
    meta?: PagingInformation;
    /**
     * 
     * @type {Array<GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationData>}
     * @memberof GameCenterAchievementRelationshipsLocalizations
     */
    data?: Array<GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationData>;
}

/**
 * Check if a given object implements the GameCenterAchievementRelationshipsLocalizations interface.
 */
export function instanceOfGameCenterAchievementRelationshipsLocalizations(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameCenterAchievementRelationshipsLocalizationsFromJSON(json: any): GameCenterAchievementRelationshipsLocalizations {
    return GameCenterAchievementRelationshipsLocalizationsFromJSONTyped(json, false);
}

export function GameCenterAchievementRelationshipsLocalizationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterAchievementRelationshipsLocalizations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : RelationshipLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationDataFromJSON)),
    };
}

export function GameCenterAchievementRelationshipsLocalizationsToJSON(value?: GameCenterAchievementRelationshipsLocalizations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': RelationshipLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(GameCenterAchievementImageRelationshipsGameCenterAchievementLocalizationDataToJSON)),
    };
}

