/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GameCenterAchievementRelationshipsGameCenterGroup } from './GameCenterAchievementRelationshipsGameCenterGroup';
import {
    GameCenterAchievementRelationshipsGameCenterGroupFromJSON,
    GameCenterAchievementRelationshipsGameCenterGroupFromJSONTyped,
    GameCenterAchievementRelationshipsGameCenterGroupToJSON,
} from './GameCenterAchievementRelationshipsGameCenterGroup';
import type { GameCenterAchievementReleaseRelationshipsGameCenterDetail } from './GameCenterAchievementReleaseRelationshipsGameCenterDetail';
import {
    GameCenterAchievementReleaseRelationshipsGameCenterDetailFromJSON,
    GameCenterAchievementReleaseRelationshipsGameCenterDetailFromJSONTyped,
    GameCenterAchievementReleaseRelationshipsGameCenterDetailToJSON,
} from './GameCenterAchievementReleaseRelationshipsGameCenterDetail';

/**
 * 
 * @export
 * @interface GameCenterAchievementCreateRequestDataRelationships
 */
export interface GameCenterAchievementCreateRequestDataRelationships {
    /**
     * 
     * @type {GameCenterAchievementReleaseRelationshipsGameCenterDetail}
     * @memberof GameCenterAchievementCreateRequestDataRelationships
     */
    gameCenterDetail?: GameCenterAchievementReleaseRelationshipsGameCenterDetail;
    /**
     * 
     * @type {GameCenterAchievementRelationshipsGameCenterGroup}
     * @memberof GameCenterAchievementCreateRequestDataRelationships
     */
    gameCenterGroup?: GameCenterAchievementRelationshipsGameCenterGroup;
}

/**
 * Check if a given object implements the GameCenterAchievementCreateRequestDataRelationships interface.
 */
export function instanceOfGameCenterAchievementCreateRequestDataRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GameCenterAchievementCreateRequestDataRelationshipsFromJSON(json: any): GameCenterAchievementCreateRequestDataRelationships {
    return GameCenterAchievementCreateRequestDataRelationshipsFromJSONTyped(json, false);
}

export function GameCenterAchievementCreateRequestDataRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameCenterAchievementCreateRequestDataRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gameCenterDetail': !exists(json, 'gameCenterDetail') ? undefined : GameCenterAchievementReleaseRelationshipsGameCenterDetailFromJSON(json['gameCenterDetail']),
        'gameCenterGroup': !exists(json, 'gameCenterGroup') ? undefined : GameCenterAchievementRelationshipsGameCenterGroupFromJSON(json['gameCenterGroup']),
    };
}

export function GameCenterAchievementCreateRequestDataRelationshipsToJSON(value?: GameCenterAchievementCreateRequestDataRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gameCenterDetail': GameCenterAchievementReleaseRelationshipsGameCenterDetailToJSON(value.gameCenterDetail),
        'gameCenterGroup': GameCenterAchievementRelationshipsGameCenterGroupToJSON(value.gameCenterGroup),
    };
}

