/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppClipAdvancedExperienceImageUpdateRequestDataAttributes } from './AppClipAdvancedExperienceImageUpdateRequestDataAttributes';
import {
    AppClipAdvancedExperienceImageUpdateRequestDataAttributesFromJSON,
    AppClipAdvancedExperienceImageUpdateRequestDataAttributesFromJSONTyped,
    AppClipAdvancedExperienceImageUpdateRequestDataAttributesToJSON,
} from './AppClipAdvancedExperienceImageUpdateRequestDataAttributes';

/**
 * 
 * @export
 * @interface InAppPurchaseImageUpdateRequestData
 */
export interface InAppPurchaseImageUpdateRequestData {
    /**
     * 
     * @type {string}
     * @memberof InAppPurchaseImageUpdateRequestData
     */
    type: InAppPurchaseImageUpdateRequestDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof InAppPurchaseImageUpdateRequestData
     */
    id: string;
    /**
     * 
     * @type {AppClipAdvancedExperienceImageUpdateRequestDataAttributes}
     * @memberof InAppPurchaseImageUpdateRequestData
     */
    attributes?: AppClipAdvancedExperienceImageUpdateRequestDataAttributes;
}


/**
 * @export
 */
export const InAppPurchaseImageUpdateRequestDataTypeEnum = {
    InAppPurchaseImages: 'inAppPurchaseImages'
} as const;
export type InAppPurchaseImageUpdateRequestDataTypeEnum = typeof InAppPurchaseImageUpdateRequestDataTypeEnum[keyof typeof InAppPurchaseImageUpdateRequestDataTypeEnum];


/**
 * Check if a given object implements the InAppPurchaseImageUpdateRequestData interface.
 */
export function instanceOfInAppPurchaseImageUpdateRequestData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function InAppPurchaseImageUpdateRequestDataFromJSON(json: any): InAppPurchaseImageUpdateRequestData {
    return InAppPurchaseImageUpdateRequestDataFromJSONTyped(json, false);
}

export function InAppPurchaseImageUpdateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InAppPurchaseImageUpdateRequestData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': !exists(json, 'attributes') ? undefined : AppClipAdvancedExperienceImageUpdateRequestDataAttributesFromJSON(json['attributes']),
    };
}

export function InAppPurchaseImageUpdateRequestDataToJSON(value?: InAppPurchaseImageUpdateRequestData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': AppClipAdvancedExperienceImageUpdateRequestDataAttributesToJSON(value.attributes),
    };
}

