/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InAppPurchaseV2RelationshipsIapPriceScheduleData } from './InAppPurchaseV2RelationshipsIapPriceScheduleData';
import {
    InAppPurchaseV2RelationshipsIapPriceScheduleDataFromJSON,
    InAppPurchaseV2RelationshipsIapPriceScheduleDataFromJSONTyped,
    InAppPurchaseV2RelationshipsIapPriceScheduleDataToJSON,
} from './InAppPurchaseV2RelationshipsIapPriceScheduleData';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
} from './RelationshipLinks';

/**
 * 
 * @export
 * @interface InAppPurchaseV2RelationshipsIapPriceSchedule
 */
export interface InAppPurchaseV2RelationshipsIapPriceSchedule {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof InAppPurchaseV2RelationshipsIapPriceSchedule
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {InAppPurchaseV2RelationshipsIapPriceScheduleData}
     * @memberof InAppPurchaseV2RelationshipsIapPriceSchedule
     */
    data?: InAppPurchaseV2RelationshipsIapPriceScheduleData;
}

/**
 * Check if a given object implements the InAppPurchaseV2RelationshipsIapPriceSchedule interface.
 */
export function instanceOfInAppPurchaseV2RelationshipsIapPriceSchedule(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InAppPurchaseV2RelationshipsIapPriceScheduleFromJSON(json: any): InAppPurchaseV2RelationshipsIapPriceSchedule {
    return InAppPurchaseV2RelationshipsIapPriceScheduleFromJSONTyped(json, false);
}

export function InAppPurchaseV2RelationshipsIapPriceScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): InAppPurchaseV2RelationshipsIapPriceSchedule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : RelationshipLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : InAppPurchaseV2RelationshipsIapPriceScheduleDataFromJSON(json['data']),
    };
}

export function InAppPurchaseV2RelationshipsIapPriceScheduleToJSON(value?: InAppPurchaseV2RelationshipsIapPriceSchedule | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': RelationshipLinksToJSON(value.links),
        'data': InAppPurchaseV2RelationshipsIapPriceScheduleDataToJSON(value.data),
    };
}

