/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InAppPurchaseImage } from './InAppPurchaseImage';
import {
    InAppPurchaseImageFromJSON,
    InAppPurchaseImageFromJSONTyped,
    InAppPurchaseImageToJSON,
} from './InAppPurchaseImage';
import type { InAppPurchaseV2 } from './InAppPurchaseV2';
import {
    InAppPurchaseV2FromJSON,
    InAppPurchaseV2FromJSONTyped,
    InAppPurchaseV2ToJSON,
} from './InAppPurchaseV2';
import type { PagedDocumentLinks } from './PagedDocumentLinks';
import {
    PagedDocumentLinksFromJSON,
    PagedDocumentLinksFromJSONTyped,
    PagedDocumentLinksToJSON,
} from './PagedDocumentLinks';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';

/**
 * 
 * @export
 * @interface InAppPurchaseImagesResponse
 */
export interface InAppPurchaseImagesResponse {
    /**
     * 
     * @type {Array<InAppPurchaseImage>}
     * @memberof InAppPurchaseImagesResponse
     */
    data: Array<InAppPurchaseImage>;
    /**
     * 
     * @type {Array<InAppPurchaseV2>}
     * @memberof InAppPurchaseImagesResponse
     */
    included?: Array<InAppPurchaseV2>;
    /**
     * 
     * @type {PagedDocumentLinks}
     * @memberof InAppPurchaseImagesResponse
     */
    links: PagedDocumentLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof InAppPurchaseImagesResponse
     */
    meta?: PagingInformation;
}

/**
 * Check if a given object implements the InAppPurchaseImagesResponse interface.
 */
export function instanceOfInAppPurchaseImagesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function InAppPurchaseImagesResponseFromJSON(json: any): InAppPurchaseImagesResponse {
    return InAppPurchaseImagesResponseFromJSONTyped(json, false);
}

export function InAppPurchaseImagesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InAppPurchaseImagesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(InAppPurchaseImageFromJSON)),
        'included': !exists(json, 'included') ? undefined : ((json['included'] as Array<any>).map(InAppPurchaseV2FromJSON)),
        'links': PagedDocumentLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
    };
}

export function InAppPurchaseImagesResponseToJSON(value?: InAppPurchaseImagesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(InAppPurchaseImageToJSON)),
        'included': value.included === undefined ? undefined : ((value.included as Array<any>).map(InAppPurchaseV2ToJSON)),
        'links': PagedDocumentLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
    };
}

