/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InAppPurchaseRelationshipsApps } from './InAppPurchaseRelationshipsApps';
import {
    InAppPurchaseRelationshipsAppsFromJSON,
    InAppPurchaseRelationshipsAppsFromJSONTyped,
    InAppPurchaseRelationshipsAppsToJSON,
} from './InAppPurchaseRelationshipsApps';

/**
 * 
 * @export
 * @interface InAppPurchaseRelationships
 */
export interface InAppPurchaseRelationships {
    /**
     * 
     * @type {InAppPurchaseRelationshipsApps}
     * @memberof InAppPurchaseRelationships
     */
    apps?: InAppPurchaseRelationshipsApps;
}

/**
 * Check if a given object implements the InAppPurchaseRelationships interface.
 */
export function instanceOfInAppPurchaseRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InAppPurchaseRelationshipsFromJSON(json: any): InAppPurchaseRelationships {
    return InAppPurchaseRelationshipsFromJSONTyped(json, false);
}

export function InAppPurchaseRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): InAppPurchaseRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apps': !exists(json, 'apps') ? undefined : InAppPurchaseRelationshipsAppsFromJSON(json['apps']),
    };
}

export function InAppPurchaseRelationshipsToJSON(value?: InAppPurchaseRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apps': InAppPurchaseRelationshipsAppsToJSON(value.apps),
    };
}

