/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MerchantIdCreateRequestData } from './MerchantIdCreateRequestData';
import {
    MerchantIdCreateRequestDataFromJSON,
    MerchantIdCreateRequestDataFromJSONTyped,
    MerchantIdCreateRequestDataToJSON,
} from './MerchantIdCreateRequestData';

/**
 * 
 * @export
 * @interface MerchantIdCreateRequest
 */
export interface MerchantIdCreateRequest {
    /**
     * 
     * @type {MerchantIdCreateRequestData}
     * @memberof MerchantIdCreateRequest
     */
    data: MerchantIdCreateRequestData;
}

/**
 * Check if a given object implements the MerchantIdCreateRequest interface.
 */
export function instanceOfMerchantIdCreateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function MerchantIdCreateRequestFromJSON(json: any): MerchantIdCreateRequest {
    return MerchantIdCreateRequestFromJSONTyped(json, false);
}

export function MerchantIdCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchantIdCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': MerchantIdCreateRequestDataFromJSON(json['data']),
    };
}

export function MerchantIdCreateRequestToJSON(value?: MerchantIdCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': MerchantIdCreateRequestDataToJSON(value.data),
    };
}

