/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NominationRelationshipsCreatedByActorData
 */
export interface NominationRelationshipsCreatedByActorData {
    /**
     * 
     * @type {string}
     * @memberof NominationRelationshipsCreatedByActorData
     */
    type: NominationRelationshipsCreatedByActorDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof NominationRelationshipsCreatedByActorData
     */
    id: string;
}


/**
 * @export
 */
export const NominationRelationshipsCreatedByActorDataTypeEnum = {
    Actors: 'actors'
} as const;
export type NominationRelationshipsCreatedByActorDataTypeEnum = typeof NominationRelationshipsCreatedByActorDataTypeEnum[keyof typeof NominationRelationshipsCreatedByActorDataTypeEnum];


/**
 * Check if a given object implements the NominationRelationshipsCreatedByActorData interface.
 */
export function instanceOfNominationRelationshipsCreatedByActorData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function NominationRelationshipsCreatedByActorDataFromJSON(json: any): NominationRelationshipsCreatedByActorData {
    return NominationRelationshipsCreatedByActorDataFromJSONTyped(json, false);
}

export function NominationRelationshipsCreatedByActorDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NominationRelationshipsCreatedByActorData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function NominationRelationshipsCreatedByActorDataToJSON(value?: NominationRelationshipsCreatedByActorData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
    };
}

