/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BundleIdCapabilityCreateRequestDataRelationshipsBundleIdData } from './BundleIdCapabilityCreateRequestDataRelationshipsBundleIdData';
import {
    BundleIdCapabilityCreateRequestDataRelationshipsBundleIdDataFromJSON,
    BundleIdCapabilityCreateRequestDataRelationshipsBundleIdDataFromJSONTyped,
    BundleIdCapabilityCreateRequestDataRelationshipsBundleIdDataToJSON,
} from './BundleIdCapabilityCreateRequestDataRelationshipsBundleIdData';
import type { RelationshipLinks } from './RelationshipLinks';
import {
    RelationshipLinksFromJSON,
    RelationshipLinksFromJSONTyped,
    RelationshipLinksToJSON,
} from './RelationshipLinks';

/**
 * 
 * @export
 * @interface ProfileRelationshipsBundleId
 */
export interface ProfileRelationshipsBundleId {
    /**
     * 
     * @type {RelationshipLinks}
     * @memberof ProfileRelationshipsBundleId
     */
    links?: RelationshipLinks;
    /**
     * 
     * @type {BundleIdCapabilityCreateRequestDataRelationshipsBundleIdData}
     * @memberof ProfileRelationshipsBundleId
     */
    data?: BundleIdCapabilityCreateRequestDataRelationshipsBundleIdData;
}

/**
 * Check if a given object implements the ProfileRelationshipsBundleId interface.
 */
export function instanceOfProfileRelationshipsBundleId(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfileRelationshipsBundleIdFromJSON(json: any): ProfileRelationshipsBundleId {
    return ProfileRelationshipsBundleIdFromJSONTyped(json, false);
}

export function ProfileRelationshipsBundleIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileRelationshipsBundleId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : RelationshipLinksFromJSON(json['links']),
        'data': !exists(json, 'data') ? undefined : BundleIdCapabilityCreateRequestDataRelationshipsBundleIdDataFromJSON(json['data']),
    };
}

export function ProfileRelationshipsBundleIdToJSON(value?: ProfileRelationshipsBundleId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': RelationshipLinksToJSON(value.links),
        'data': BundleIdCapabilityCreateRequestDataRelationshipsBundleIdDataToJSON(value.data),
    };
}

