/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MerchantIdRelationshipsCertificates } from './MerchantIdRelationshipsCertificates';
import {
    MerchantIdRelationshipsCertificatesFromJSON,
    MerchantIdRelationshipsCertificatesFromJSONTyped,
    MerchantIdRelationshipsCertificatesToJSON,
} from './MerchantIdRelationshipsCertificates';
import type { ProfileRelationshipsBundleId } from './ProfileRelationshipsBundleId';
import {
    ProfileRelationshipsBundleIdFromJSON,
    ProfileRelationshipsBundleIdFromJSONTyped,
    ProfileRelationshipsBundleIdToJSON,
} from './ProfileRelationshipsBundleId';
import type { ProfileRelationshipsDevices } from './ProfileRelationshipsDevices';
import {
    ProfileRelationshipsDevicesFromJSON,
    ProfileRelationshipsDevicesFromJSONTyped,
    ProfileRelationshipsDevicesToJSON,
} from './ProfileRelationshipsDevices';

/**
 * 
 * @export
 * @interface ProfileRelationships
 */
export interface ProfileRelationships {
    /**
     * 
     * @type {ProfileRelationshipsBundleId}
     * @memberof ProfileRelationships
     */
    bundleId?: ProfileRelationshipsBundleId;
    /**
     * 
     * @type {ProfileRelationshipsDevices}
     * @memberof ProfileRelationships
     */
    devices?: ProfileRelationshipsDevices;
    /**
     * 
     * @type {MerchantIdRelationshipsCertificates}
     * @memberof ProfileRelationships
     */
    certificates?: MerchantIdRelationshipsCertificates;
}

/**
 * Check if a given object implements the ProfileRelationships interface.
 */
export function instanceOfProfileRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfileRelationshipsFromJSON(json: any): ProfileRelationships {
    return ProfileRelationshipsFromJSONTyped(json, false);
}

export function ProfileRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bundleId': !exists(json, 'bundleId') ? undefined : ProfileRelationshipsBundleIdFromJSON(json['bundleId']),
        'devices': !exists(json, 'devices') ? undefined : ProfileRelationshipsDevicesFromJSON(json['devices']),
        'certificates': !exists(json, 'certificates') ? undefined : MerchantIdRelationshipsCertificatesFromJSON(json['certificates']),
    };
}

export function ProfileRelationshipsToJSON(value?: ProfileRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bundleId': ProfileRelationshipsBundleIdToJSON(value.bundleId),
        'devices': ProfileRelationshipsDevicesToJSON(value.devices),
        'certificates': MerchantIdRelationshipsCertificatesToJSON(value.certificates),
    };
}

