/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AnalyticsReportRequestCreateRequestDataRelationshipsApp } from './AnalyticsReportRequestCreateRequestDataRelationshipsApp';
import {
    AnalyticsReportRequestCreateRequestDataRelationshipsAppFromJSON,
    AnalyticsReportRequestCreateRequestDataRelationshipsAppFromJSONTyped,
    AnalyticsReportRequestCreateRequestDataRelationshipsAppToJSON,
} from './AnalyticsReportRequestCreateRequestDataRelationshipsApp';
import type { InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2 } from './InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2';
import {
    InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2FromJSON,
    InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2FromJSONTyped,
    InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2ToJSON,
} from './InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2';
import type { PromotedPurchaseRelationshipsSubscription } from './PromotedPurchaseRelationshipsSubscription';
import {
    PromotedPurchaseRelationshipsSubscriptionFromJSON,
    PromotedPurchaseRelationshipsSubscriptionFromJSONTyped,
    PromotedPurchaseRelationshipsSubscriptionToJSON,
} from './PromotedPurchaseRelationshipsSubscription';

/**
 * 
 * @export
 * @interface PromotedPurchaseCreateRequestDataRelationships
 */
export interface PromotedPurchaseCreateRequestDataRelationships {
    /**
     * 
     * @type {AnalyticsReportRequestCreateRequestDataRelationshipsApp}
     * @memberof PromotedPurchaseCreateRequestDataRelationships
     */
    app: AnalyticsReportRequestCreateRequestDataRelationshipsApp;
    /**
     * 
     * @type {InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2}
     * @memberof PromotedPurchaseCreateRequestDataRelationships
     */
    inAppPurchaseV2?: InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2;
    /**
     * 
     * @type {PromotedPurchaseRelationshipsSubscription}
     * @memberof PromotedPurchaseCreateRequestDataRelationships
     */
    subscription?: PromotedPurchaseRelationshipsSubscription;
}

/**
 * Check if a given object implements the PromotedPurchaseCreateRequestDataRelationships interface.
 */
export function instanceOfPromotedPurchaseCreateRequestDataRelationships(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "app" in value;

    return isInstance;
}

export function PromotedPurchaseCreateRequestDataRelationshipsFromJSON(json: any): PromotedPurchaseCreateRequestDataRelationships {
    return PromotedPurchaseCreateRequestDataRelationshipsFromJSONTyped(json, false);
}

export function PromotedPurchaseCreateRequestDataRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromotedPurchaseCreateRequestDataRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'app': AnalyticsReportRequestCreateRequestDataRelationshipsAppFromJSON(json['app']),
        'inAppPurchaseV2': !exists(json, 'inAppPurchaseV2') ? undefined : InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2FromJSON(json['inAppPurchaseV2']),
        'subscription': !exists(json, 'subscription') ? undefined : PromotedPurchaseRelationshipsSubscriptionFromJSON(json['subscription']),
    };
}

export function PromotedPurchaseCreateRequestDataRelationshipsToJSON(value?: PromotedPurchaseCreateRequestDataRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'app': AnalyticsReportRequestCreateRequestDataRelationshipsAppToJSON(value.app),
        'inAppPurchaseV2': InAppPurchaseAppStoreReviewScreenshotRelationshipsInAppPurchaseV2ToJSON(value.inAppPurchaseV2),
        'subscription': PromotedPurchaseRelationshipsSubscriptionToJSON(value.subscription),
    };
}

