/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PagedDocumentLinks } from './PagedDocumentLinks';
import {
    PagedDocumentLinksFromJSON,
    PagedDocumentLinksFromJSONTyped,
    PagedDocumentLinksToJSON,
} from './PagedDocumentLinks';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';
import type { Subscription } from './Subscription';
import {
    SubscriptionFromJSON,
    SubscriptionFromJSONTyped,
    SubscriptionToJSON,
} from './Subscription';
import type { SubscriptionImage } from './SubscriptionImage';
import {
    SubscriptionImageFromJSON,
    SubscriptionImageFromJSONTyped,
    SubscriptionImageToJSON,
} from './SubscriptionImage';

/**
 * 
 * @export
 * @interface SubscriptionImagesResponse
 */
export interface SubscriptionImagesResponse {
    /**
     * 
     * @type {Array<SubscriptionImage>}
     * @memberof SubscriptionImagesResponse
     */
    data: Array<SubscriptionImage>;
    /**
     * 
     * @type {Array<Subscription>}
     * @memberof SubscriptionImagesResponse
     */
    included?: Array<Subscription>;
    /**
     * 
     * @type {PagedDocumentLinks}
     * @memberof SubscriptionImagesResponse
     */
    links: PagedDocumentLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof SubscriptionImagesResponse
     */
    meta?: PagingInformation;
}

/**
 * Check if a given object implements the SubscriptionImagesResponse interface.
 */
export function instanceOfSubscriptionImagesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function SubscriptionImagesResponseFromJSON(json: any): SubscriptionImagesResponse {
    return SubscriptionImagesResponseFromJSONTyped(json, false);
}

export function SubscriptionImagesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionImagesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(SubscriptionImageFromJSON)),
        'included': !exists(json, 'included') ? undefined : ((json['included'] as Array<any>).map(SubscriptionFromJSON)),
        'links': PagedDocumentLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
    };
}

export function SubscriptionImagesResponseToJSON(value?: SubscriptionImagesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(SubscriptionImageToJSON)),
        'included': value.included === undefined ? undefined : ((value.included as Array<any>).map(SubscriptionToJSON)),
        'links': PagedDocumentLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
    };
}

