/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SubscriptionIntroductoryOfferInlineCreateAttributes } from './SubscriptionIntroductoryOfferInlineCreateAttributes';
import {
    SubscriptionIntroductoryOfferInlineCreateAttributesFromJSON,
    SubscriptionIntroductoryOfferInlineCreateAttributesFromJSONTyped,
    SubscriptionIntroductoryOfferInlineCreateAttributesToJSON,
} from './SubscriptionIntroductoryOfferInlineCreateAttributes';
import type { SubscriptionIntroductoryOfferRelationships } from './SubscriptionIntroductoryOfferRelationships';
import {
    SubscriptionIntroductoryOfferRelationshipsFromJSON,
    SubscriptionIntroductoryOfferRelationshipsFromJSONTyped,
    SubscriptionIntroductoryOfferRelationshipsToJSON,
} from './SubscriptionIntroductoryOfferRelationships';

/**
 * 
 * @export
 * @interface SubscriptionIntroductoryOfferInlineCreate
 */
export interface SubscriptionIntroductoryOfferInlineCreate {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionIntroductoryOfferInlineCreate
     */
    type: SubscriptionIntroductoryOfferInlineCreateTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionIntroductoryOfferInlineCreate
     */
    id?: string;
    /**
     * 
     * @type {SubscriptionIntroductoryOfferInlineCreateAttributes}
     * @memberof SubscriptionIntroductoryOfferInlineCreate
     */
    attributes: SubscriptionIntroductoryOfferInlineCreateAttributes;
    /**
     * 
     * @type {SubscriptionIntroductoryOfferRelationships}
     * @memberof SubscriptionIntroductoryOfferInlineCreate
     */
    relationships?: SubscriptionIntroductoryOfferRelationships;
}


/**
 * @export
 */
export const SubscriptionIntroductoryOfferInlineCreateTypeEnum = {
    SubscriptionIntroductoryOffers: 'subscriptionIntroductoryOffers'
} as const;
export type SubscriptionIntroductoryOfferInlineCreateTypeEnum = typeof SubscriptionIntroductoryOfferInlineCreateTypeEnum[keyof typeof SubscriptionIntroductoryOfferInlineCreateTypeEnum];


/**
 * Check if a given object implements the SubscriptionIntroductoryOfferInlineCreate interface.
 */
export function instanceOfSubscriptionIntroductoryOfferInlineCreate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function SubscriptionIntroductoryOfferInlineCreateFromJSON(json: any): SubscriptionIntroductoryOfferInlineCreate {
    return SubscriptionIntroductoryOfferInlineCreateFromJSONTyped(json, false);
}

export function SubscriptionIntroductoryOfferInlineCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionIntroductoryOfferInlineCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'attributes': SubscriptionIntroductoryOfferInlineCreateAttributesFromJSON(json['attributes']),
        'relationships': !exists(json, 'relationships') ? undefined : SubscriptionIntroductoryOfferRelationshipsFromJSON(json['relationships']),
    };
}

export function SubscriptionIntroductoryOfferInlineCreateToJSON(value?: SubscriptionIntroductoryOfferInlineCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': SubscriptionIntroductoryOfferInlineCreateAttributesToJSON(value.attributes),
        'relationships': SubscriptionIntroductoryOfferRelationshipsToJSON(value.relationships),
    };
}

