/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResourceLinks } from './ResourceLinks';
import {
    ResourceLinksFromJSON,
    ResourceLinksFromJSONTyped,
    ResourceLinksToJSON,
} from './ResourceLinks';
import type { SubscriptionOfferCodeOneTimeUseCodeAttributes } from './SubscriptionOfferCodeOneTimeUseCodeAttributes';
import {
    SubscriptionOfferCodeOneTimeUseCodeAttributesFromJSON,
    SubscriptionOfferCodeOneTimeUseCodeAttributesFromJSONTyped,
    SubscriptionOfferCodeOneTimeUseCodeAttributesToJSON,
} from './SubscriptionOfferCodeOneTimeUseCodeAttributes';
import type { SubscriptionOfferCodeOneTimeUseCodeRelationships } from './SubscriptionOfferCodeOneTimeUseCodeRelationships';
import {
    SubscriptionOfferCodeOneTimeUseCodeRelationshipsFromJSON,
    SubscriptionOfferCodeOneTimeUseCodeRelationshipsFromJSONTyped,
    SubscriptionOfferCodeOneTimeUseCodeRelationshipsToJSON,
} from './SubscriptionOfferCodeOneTimeUseCodeRelationships';

/**
 * 
 * @export
 * @interface SubscriptionOfferCodeOneTimeUseCode
 */
export interface SubscriptionOfferCodeOneTimeUseCode {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionOfferCodeOneTimeUseCode
     */
    type: SubscriptionOfferCodeOneTimeUseCodeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionOfferCodeOneTimeUseCode
     */
    id: string;
    /**
     * 
     * @type {SubscriptionOfferCodeOneTimeUseCodeAttributes}
     * @memberof SubscriptionOfferCodeOneTimeUseCode
     */
    attributes?: SubscriptionOfferCodeOneTimeUseCodeAttributes;
    /**
     * 
     * @type {SubscriptionOfferCodeOneTimeUseCodeRelationships}
     * @memberof SubscriptionOfferCodeOneTimeUseCode
     */
    relationships?: SubscriptionOfferCodeOneTimeUseCodeRelationships;
    /**
     * 
     * @type {ResourceLinks}
     * @memberof SubscriptionOfferCodeOneTimeUseCode
     */
    links?: ResourceLinks;
}


/**
 * @export
 */
export const SubscriptionOfferCodeOneTimeUseCodeTypeEnum = {
    SubscriptionOfferCodeOneTimeUseCodes: 'subscriptionOfferCodeOneTimeUseCodes'
} as const;
export type SubscriptionOfferCodeOneTimeUseCodeTypeEnum = typeof SubscriptionOfferCodeOneTimeUseCodeTypeEnum[keyof typeof SubscriptionOfferCodeOneTimeUseCodeTypeEnum];


/**
 * Check if a given object implements the SubscriptionOfferCodeOneTimeUseCode interface.
 */
export function instanceOfSubscriptionOfferCodeOneTimeUseCode(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function SubscriptionOfferCodeOneTimeUseCodeFromJSON(json: any): SubscriptionOfferCodeOneTimeUseCode {
    return SubscriptionOfferCodeOneTimeUseCodeFromJSONTyped(json, false);
}

export function SubscriptionOfferCodeOneTimeUseCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionOfferCodeOneTimeUseCode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': !exists(json, 'attributes') ? undefined : SubscriptionOfferCodeOneTimeUseCodeAttributesFromJSON(json['attributes']),
        'relationships': !exists(json, 'relationships') ? undefined : SubscriptionOfferCodeOneTimeUseCodeRelationshipsFromJSON(json['relationships']),
        'links': !exists(json, 'links') ? undefined : ResourceLinksFromJSON(json['links']),
    };
}

export function SubscriptionOfferCodeOneTimeUseCodeToJSON(value?: SubscriptionOfferCodeOneTimeUseCode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': SubscriptionOfferCodeOneTimeUseCodeAttributesToJSON(value.attributes),
        'relationships': SubscriptionOfferCodeOneTimeUseCodeRelationshipsToJSON(value.relationships),
        'links': ResourceLinksToJSON(value.links),
    };
}

