/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppClipAdvancedExperienceImageCreateRequestDataAttributes } from './AppClipAdvancedExperienceImageCreateRequestDataAttributes';
import {
    AppClipAdvancedExperienceImageCreateRequestDataAttributesFromJSON,
    AppClipAdvancedExperienceImageCreateRequestDataAttributesFromJSONTyped,
    AppClipAdvancedExperienceImageCreateRequestDataAttributesToJSON,
} from './AppClipAdvancedExperienceImageCreateRequestDataAttributes';
import type { SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationships } from './SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationships';
import {
    SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationshipsFromJSON,
    SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationshipsFromJSONTyped,
    SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationshipsToJSON,
} from './SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationships';

/**
 * 
 * @export
 * @interface SubscriptionImageCreateRequestData
 */
export interface SubscriptionImageCreateRequestData {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionImageCreateRequestData
     */
    type: SubscriptionImageCreateRequestDataTypeEnum;
    /**
     * 
     * @type {AppClipAdvancedExperienceImageCreateRequestDataAttributes}
     * @memberof SubscriptionImageCreateRequestData
     */
    attributes: AppClipAdvancedExperienceImageCreateRequestDataAttributes;
    /**
     * 
     * @type {SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationships}
     * @memberof SubscriptionImageCreateRequestData
     */
    relationships: SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationships;
}


/**
 * @export
 */
export const SubscriptionImageCreateRequestDataTypeEnum = {
    SubscriptionImages: 'subscriptionImages'
} as const;
export type SubscriptionImageCreateRequestDataTypeEnum = typeof SubscriptionImageCreateRequestDataTypeEnum[keyof typeof SubscriptionImageCreateRequestDataTypeEnum];


/**
 * Check if a given object implements the SubscriptionImageCreateRequestData interface.
 */
export function instanceOfSubscriptionImageCreateRequestData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "relationships" in value;

    return isInstance;
}

export function SubscriptionImageCreateRequestDataFromJSON(json: any): SubscriptionImageCreateRequestData {
    return SubscriptionImageCreateRequestDataFromJSONTyped(json, false);
}

export function SubscriptionImageCreateRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionImageCreateRequestData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'attributes': AppClipAdvancedExperienceImageCreateRequestDataAttributesFromJSON(json['attributes']),
        'relationships': SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationshipsFromJSON(json['relationships']),
    };
}

export function SubscriptionImageCreateRequestDataToJSON(value?: SubscriptionImageCreateRequestData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'attributes': AppClipAdvancedExperienceImageCreateRequestDataAttributesToJSON(value.attributes),
        'relationships': SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationshipsToJSON(value.relationships),
    };
}

