/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NominationUpdateRequestDataRelationshipsRelatedApps } from './NominationUpdateRequestDataRelationshipsRelatedApps';
import {
    NominationUpdateRequestDataRelationshipsRelatedAppsFromJSON,
    NominationUpdateRequestDataRelationshipsRelatedAppsFromJSONTyped,
    NominationUpdateRequestDataRelationshipsRelatedAppsToJSON,
} from './NominationUpdateRequestDataRelationshipsRelatedApps';

/**
 * 
 * @export
 * @interface UserInvitationCreateRequestDataRelationships
 */
export interface UserInvitationCreateRequestDataRelationships {
    /**
     * 
     * @type {NominationUpdateRequestDataRelationshipsRelatedApps}
     * @memberof UserInvitationCreateRequestDataRelationships
     */
    visibleApps?: NominationUpdateRequestDataRelationshipsRelatedApps;
}

/**
 * Check if a given object implements the UserInvitationCreateRequestDataRelationships interface.
 */
export function instanceOfUserInvitationCreateRequestDataRelationships(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserInvitationCreateRequestDataRelationshipsFromJSON(json: any): UserInvitationCreateRequestDataRelationships {
    return UserInvitationCreateRequestDataRelationshipsFromJSONTyped(json, false);
}

export function UserInvitationCreateRequestDataRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInvitationCreateRequestDataRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'visibleApps': !exists(json, 'visibleApps') ? undefined : NominationUpdateRequestDataRelationshipsRelatedAppsFromJSON(json['visibleApps']),
    };
}

export function UserInvitationCreateRequestDataRelationshipsToJSON(value?: UserInvitationCreateRequestDataRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'visibleApps': NominationUpdateRequestDataRelationshipsRelatedAppsToJSON(value.visibleApps),
    };
}

