/* tslint:disable */
/* eslint-disable */
/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PagedDocumentLinks } from './PagedDocumentLinks';
import {
    PagedDocumentLinksFromJSON,
    PagedDocumentLinksFromJSONTyped,
    PagedDocumentLinksToJSON,
} from './PagedDocumentLinks';
import type { PagingInformation } from './PagingInformation';
import {
    PagingInformationFromJSON,
    PagingInformationFromJSONTyped,
    PagingInformationToJSON,
} from './PagingInformation';
import type { SubscriptionOfferCodePricesResponseIncludedInner } from './SubscriptionOfferCodePricesResponseIncludedInner';
import {
    SubscriptionOfferCodePricesResponseIncludedInnerFromJSON,
    SubscriptionOfferCodePricesResponseIncludedInnerFromJSONTyped,
    SubscriptionOfferCodePricesResponseIncludedInnerToJSON,
} from './SubscriptionOfferCodePricesResponseIncludedInner';
import type { WinBackOfferPrice } from './WinBackOfferPrice';
import {
    WinBackOfferPriceFromJSON,
    WinBackOfferPriceFromJSONTyped,
    WinBackOfferPriceToJSON,
} from './WinBackOfferPrice';

/**
 * 
 * @export
 * @interface WinBackOfferPricesResponse
 */
export interface WinBackOfferPricesResponse {
    /**
     * 
     * @type {Array<WinBackOfferPrice>}
     * @memberof WinBackOfferPricesResponse
     */
    data: Array<WinBackOfferPrice>;
    /**
     * 
     * @type {Array<SubscriptionOfferCodePricesResponseIncludedInner>}
     * @memberof WinBackOfferPricesResponse
     */
    included?: Array<SubscriptionOfferCodePricesResponseIncludedInner>;
    /**
     * 
     * @type {PagedDocumentLinks}
     * @memberof WinBackOfferPricesResponse
     */
    links: PagedDocumentLinks;
    /**
     * 
     * @type {PagingInformation}
     * @memberof WinBackOfferPricesResponse
     */
    meta?: PagingInformation;
}

/**
 * Check if a given object implements the WinBackOfferPricesResponse interface.
 */
export function instanceOfWinBackOfferPricesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function WinBackOfferPricesResponseFromJSON(json: any): WinBackOfferPricesResponse {
    return WinBackOfferPricesResponseFromJSONTyped(json, false);
}

export function WinBackOfferPricesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WinBackOfferPricesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(WinBackOfferPriceFromJSON)),
        'included': !exists(json, 'included') ? undefined : ((json['included'] as Array<any>).map(SubscriptionOfferCodePricesResponseIncludedInnerFromJSON)),
        'links': PagedDocumentLinksFromJSON(json['links']),
        'meta': !exists(json, 'meta') ? undefined : PagingInformationFromJSON(json['meta']),
    };
}

export function WinBackOfferPricesResponseToJSON(value?: WinBackOfferPricesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(WinBackOfferPriceToJSON)),
        'included': value.included === undefined ? undefined : ((value.included as Array<any>).map(SubscriptionOfferCodePricesResponseIncludedInnerToJSON)),
        'links': PagedDocumentLinksToJSON(value.links),
        'meta': PagingInformationToJSON(value.meta),
    };
}

